kafka {
  bootstrap-servers = "localhost:9092"
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  topics {
    live-balls = "cricket-live-balls"
    live-matches = "cricket-live-matches"
    cricsheet-batch = "cricket-batch"
  }
  consumer-group = "cricket-spark-consumer"
  producer {
    acks = "all"
    retries = 3
    batch-size = 16384
    linger-ms = 1
    buffer-memory = 33554432
  }
}
