include "kafka.conf"
include "delta.conf"
include "cricapi.conf"

app {
  name = "cricket-analytics-platform"
  version = "1.0.0"
  environment = "local"
  environment = ${?APP_ENV}
}

spark {
  master = "local[*]"
  master = ${?SPARK_MASTER}
  app-name = "CricketAnalyticsPlatform"
  checkpoint-base = "/tmp/cricket-checkpoints"
  checkpoint-base = ${?CHECKPOINT_BASE}
}
