delta {
  base-path = "/tmp/cricket-delta"
  base-path = ${?DELTA_BASE_PATH}
  bronze {
    live-balls = ${delta.base-path}"/bronze/live_balls"
    batch-deliveries = ${delta.base-path}"/bronze/cricsheet_deliveries"
  }
  silver {
    live-balls = ${delta.base-path}"/silver/live_balls"
    deliveries = ${delta.base-path}"/silver/deliveries"
  }
  gold {
    live-kpis = ${delta.base-path}"/gold/live_kpis"
    batch-kpis = ${delta.base-path}"/gold/batch_kpis"
  }
}
